language: java

jdk:
  - oraclejdk8

notifications:
  email:
    - mbatchakwe.kentharold@gmail.com

before_script:
  sudo apt-get update && sudo apt-get install oracle-java8-installer

script: mvn clean install